# Generated by Django 4.0.2 on 2022-02-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_po_created_at_remove_po_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='concept',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
