# Generated by Django 4.0.2 on 2022-02-24 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_concept_created_at_remove_concept_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
