# Generated by Django 4.0.2 on 2022-02-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_po_concept_concept_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='client',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
