# Generated by Django 4.0.2 on 2022-02-24 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_po_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
