# Generated by Django 4.0.2 on 2022-02-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_po_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='quantity',
            new_name='Cantidad',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='description',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='notes',
            new_name='Notas',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='total',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='unit_price',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='unit',
            new_name='Unidad',
        ),
    ]
